---
# tasks file for koji-db

- name: Main | Remove nodocs from yum.conf
  lineinfile: dest=/etc/yum.conf state=absent regexp="^tsflags="
  tags:
    - yum
    - koji-package
    - koji-db

- name: Main | Install koji package with schema
  yum: name=koji state=present update_cache=yes
  tags:
    - yum
    - koji-package
    - koji-db

- name: Main | Import koji schema file'
  shell: "psql -U {{ koji_db_user }} {{ koji_dbname }} < $(rpm -qd koji | grep schema.sql) && touch /etc/koji.schema.done"
  args:
    creates: "/etc/koji.schema.done"
  tags:
    - koji-schema
    - koji-db

- name: Main | Put insert_kojiadmin.sql to /etc/koji.kojiadmin.sql
  copy: src=insert_kojiadmin.sql dest=/etc/koji.kojiadmin.sql owner=root group=root mode=0644
  tags:
    - koji-schema
    - koji-db

- name: Main | Insert kojiadmin into users table
  shell: "psql -U {{ koji_db_user }} {{ koji_dbname }} < /etc/koji.kojiadmin.sql && touch /etc/koji.kojiadmin.insert.done"
  args:
    creates: "/etc/koji.kojiadmin.insert.done"
  tags:
    - koji-schema
    - koji-db
