---

- name: Install | Install required Packages
  yum: name={{item}} state=installed
  with_items:
    - koji-hub
    - httpd
    - mod_ssl
    - mod_python
    - sudo
    - tar
  when: ansible_distribution_major_version == '6'
  tags:
    - hub
    - kojiadmin

- name: Install | Install required Packages
  yum: name={{item}} state=installed
  with_items:
    - koji-hub
    - httpd
    - mod_ssl
  when: ansible_distribution_major_version == '7'
  tags:
    - hub
